name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths: ['metadata/**', 'targets/**']

jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for adding targets changes into the signing event branch
      issues: write
      actions: write # for dispatching another signing-event workflow

    steps:
      - name: Signing event
        uses: theupdateframework/tuf-on-ci/actions/signing-event@6e6d3fbf63d714721cd6a693b2b9f599ebd94f19 # rc-v0.4.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
